version: '3.5'
services:
    db:
     image: mongo
     ports:
        - 27017:27017
    
    authapi:
      image: auth-api
      ports:
        - 7000:7000
      environment:
          MONGODB_SERVER: "mongodb://db:27017/AuthBooks" 

    favoriteapi:
      image: favorite-api
      ports:
        - 8001:8001
      environment:
          MONGODB_SERVER: "mongodb://db:27017/FavoriteBooks"  

    bookapi:
       image: book-api
       ports:
         - 8000:8000
       
    frontend:
       image: book-app
       ports:
        - 3000:80